prometheus/consul_exporter

Dockerfile
consul_exporter does not use golang/glog
=> Dockerfile : no -logtostderr cmd

consul_exporter.go
This appears to work well here. 
I'm not too proficient in go yet so I'd appreciate feedback. 
In particular, I suspect `kv.List` might be blocking so it might be worthwhile to do this as a goroutine that puts the pairs on a channel - on the other hand, if I understand correctly `setMetrics` doesn't do this either, so perhaps it's inconsequential.
=> Add support for exposing key-value pairs (implements #7)

Makefile.COMMON, consul_exporter.go
We want to know when each individual health check failed so that we can investigate why a particular service wasn't available via service discovery. Therefore, a new metric `consul_health_service_status` was added.
This PR also cleans up several issues with the code and consolidates some other metrics. Most notably:
* `consul_catalog_service_nodes` has been removed as it is redundant (the number of nodes can be calculated with `count()`)
* `consul_catalog_service_node_healthy` uses the service ID instead of the name, as the latter isn't unique and caused metrics to be overwritten.
@ewr @fabxc @brian-brazil 
This PR supersedes #11 which did similar cleanups. It might be easier to review each individual commit.
=> Export state of all health checks

consul_exporter.go
Per some mailing list discussion, I believe this is considered best practice. It's also shorter: since the metrics aren't persistent, there's no need to reset them every time, etc.
=> use ConstMetrics instead of sharing with lock

consul_exporter.go, consul_exporter_test.go
This preserves existing functionality. If `-consul.server` begins w/ `http://` or `https://` that scheme will be used. HTTP is the fallback scheme if no scheme is provided.
/cc @grobie
=> use scheme if provided to -consul.server flag

consul_exporter.go, consul_exporter_test.go
So we can alert when a consul instance doesn't know about its master.
=> Expose /v1/status/leader as a metric

README.md, consul_exporter.go
The consul/api package supports several config options to configure
their ACL tokens or also TLS. Instead of reimplementing these options in
the consul_exporter, using their DefaultConfig() intializer allows us to
delegate the implementation and tests to them.
I'll add full integration tests later. Closes #39.
@deepthawtz @discordianfish
=> Support standard consul api package config options

consul_exporter.go
This makes it slighlty more usable when one has a lot of services.
Tested with 10k+ services (10s timeout).
In order to make it more usable this should probably be fetched
periodically and asynchronously even if it means exposing a slightly
stale status.
=> Fetch health summaries in parallel

Dockerfile
Replacing MAINTAINER instruction with LABEL in Dockerfile since maintainer is deprecated:
https://docs.docker.com/engine/reference/builder/#maintainer-deprecated
Resolves: https://github.com/prometheus/consul_exporter/issues/87
=> Replacing MAINTAINER instruction with LABEL in Dockerfile

Dockerfile, Makefile
It also fixes the jobs building the images which have been broken by #118.
=> Build ARM container images

consul_exporter.go
This patch exposes the InsecureSkipVerify option of the consul TLS configuration via a command-line flag `--consul.insecure`. This defaults to `false`, so the default behaviour is unchanged (full TLS verification).
=> Add --consul.insecure flag to skip TLS verification.

consul_exporter.go
This 'pretty' prints the Options JSON into the default webpage if the user requests `/`. Makes for ever so slightly nicer reading of the options.
=> Trivial tidying of the HTML output

consul_exporter.go, go.mod
This PR changes the flow of the scraper to not bail out on specific API failures, after `consul` is deemed to be `up`. If one of the `consul` APIs fail, this metric datapoint will be null, which should work well with things like dashboards and/or monitoring (up to the user to treat missing as breaching or not).
=> #143 Handle Consul errors in a consistent fashion

consul_exporter.go
Endpoint that indicates if the Consul Exporter is healthy.
Should close #150
=> Adding /-/healthy and /-/ready endpoints

README.md, consul_exporter.go, consul_exporter_test.go
My organization would like to surface more human readable check names as an option for quickly identifying an alert for a service check. Check IDs aren't human friendly when seeing the alert from alertmanager.
Signed-off-by: Andrew Cornies <acornies@gmail.com>
=> Add new metric for Consul check names:

.promu.yml, cmd/consul_exporter/consul_exporter.go, pkg/exporter/consul_exporter.go, pkg/exporter/consul_exporter_test.go
This allows clients to import the exporter as a library. Corresponds to similar changes made in prometheus/memcached_exporter#97.
Signed-off-by: Robert Fratto <robertfratto@gmail.com>
=> Move exporter logic to dedicated package

README.md
Command-Line argument package `kingpin` uses a unique mechanism to disable bool flags by prefixing with no. As this is non-intuitive and requires some understanding of `kingpin`, suggesting an update in the documentation to better understand how to configure arguments.
enable: `--<name>`
disabled: `--no-<name>`
@simonpasquier
=> update documentation for disabling cmd-line flag of type bool 

README.md, pkg/exporter/consul_exporter.go
Adds metrics to collect consul wan members status.
=> Add metric to collect wan status

.circleci/config.yml
This is to check that https://github.com/prometheus/circleci/pull/26 works as intended. The rest of the repositories should be updated by the periodic `sync_repo` job but I felt that it would be good to validate end-to-end with one repository.
And from the build job's [logs](https://app.circleci.com/pipelines/github/prometheus/consul_exporter/278/workflows/8516e3ab-83c2-4a32-8258-1c6d117984e1/jobs/849/parallel-runs/0/steps/0-0), the machine executor seems to deploy a supported Ubuntu version.
=> .circleci: update orb version

cmd/consul_exporter/consul_exporter.go, pkg/exporter/consul_exporter.go
in agent only mode, the exporter exposes information only about services registered on the local agent
this is useful for cases when one uses consul with acl system enabled, so some services might not make to catalog because the agent doesn't have permission to register them
it would be nice to have metrics from both sides for comparison
=> Add flag for running agent only mode

README.md
Add missing explanation for `consul.agent-only` in the README.md
=> docs: add consul.agent-only documentation

pkg/exporter/consul_exporter.go
I have made a mistake in the origin PR of mine, in the case of agent side collection of services we need the service's name instead of the service instance's name.
=> fix service mapping

pkg/exporter/consul_exporter.go
One problem we've experienced is that when you register a service in consul it is case sensitive. so for example, registering 
`redis` and `REDIS` will register 2 services. However the "gotcha" is that instances of _EITHER_ service will tie to _BOTH_ services. 
example:
```
redis service
-------------
instance-1-redis
instance 2-redis
instance-1-REDIS
instance-2-REDIS
REDIS service
-------------
instance-1-REDIS
instance-2-REDIS
instance-1-redis
instance 2-redis
```
This creates duplicate metric entries for consul_service_tag and consul_node_healthy metrics when in reality it shouldn't fail on this. I do say i mostly blame consul for the way its done, but from what i know it was done like that on purpose because that is how the DNS is going to work with consul (case _INSENSITIVE_). 
This …
=> fixing duplicate services that are seperate only by casing
