- consul_exporter.go
This makes it possible to review arbitrary checks on a node that are not attached to a service. This makes it possible for Prometheus, with Consul's help, take over what something like Nagios/Sensu does with running local checks that are simple yes/no style checks.
Our first use case being a check to ensure that our config management agent runs and finishes on the correct schedule:
```consul_agent_check{check="localansible_run",node="sjc1-a5-25",state="critical"} 1```
I was going to ask for this, but figured maybe a PR was a better way to start the conversation. I welcome any feedback or concerns, but keen to see this functionality get merged.
> report checks not associated with services

- README.md
@ewr and @grobie - Because not all users want to read the code to figure this out.
> Table describing exported metrics for the README

- consul_exporter.go
> Add label with consul service name to health summary.

- README.md
- consul_exporter.go
> Provide consul health check status as label

- consul_exporter.go
Also display them on / to make it easier to debug issues.
> Add AllowStale/RequireConsistent/Datacenter flags

- .travis.yml
- Makefile
- Makefile.common
> Use Makefile.common from Prometheus

- Makefile.common
- consul_exporter.go
- consul_exporter_test.go
* Add copyright headers.
* Update Makfile.common.
> Fix up copyright headers

- Makefile
- consul_exporter.go
- vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator.go
- vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator_1_8.go
- vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator_pre_1_8.go
- vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go
- vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
- vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client_1_8.go
- vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
- vendor/modules.txt
This _will_ change the metrics about the exposition itself.
Signed-off-by: beorn7 <beorn@grafana.com>
> Replace deprecated prometheus.Handler with promhttp.Handler

- MAINTAINERS.md
I don't have the time anymore to fulfill the responsibilities of proper
maintaining this exporter. Simon offered to step in, thanks a lot!
Signed-off-by: Tobias Schmidt <tobidt@gmail.com>
> Change maintainer to Simon Pasquier

- .dockerignore
`.dockerignore` file got in the way...
> Fix build for ARM container images

- README.md
- consul_exporter.go
- consul_exporter_test.go
> expose agent members status #84

- consul_exporter.go
- consul_exporter_test.go
> Fix label clashes

- consul_exporter.go
> Increasing default timeout

- .circleci/config.yml
- .promu.yml
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>
> Bump golang version to 1.14

- consul_exporter.go
Recommited.
Close https://github.com/prometheus/consul_exporter/issues/102.
Close https://github.com/prometheus/consul_exporter/pull/94.
> Provide an option to limit the maximum concurrent request to consul.

- consul_exporter.go
- consul_exporter_test.go
Alternative implementation of #178
Closes #178
Closes #176
> Fix consul_exporter hanging when services > allowed requests

- README.md
Fixes a broken link in the main `README.md`.
> Fix docker hub link

- README.md
add consul_service_tag exported metrics and correction some labels infos
> correction exported metrics some of the information

- .circleci/config.yml
- .promu.yml
- go.mod
- go.sum
* Update to Go 1.19.
* Bump some modules.
Signed-off-by: SuperQ <superq@gmail.com>
> Update Go version

- README.md
- cmd/consul_exporter/consul_exporter.go
Hello, 
Adding version flag to get infos on consul_exporter.
> feat: add version flag
